### PR TITLE
Fix for issue #13

### PR DESCRIPTION
**Pull request by RobertK66**
* a bug fix for issue https://github.com/1manprojects/one_Sgp4/issues/13
* Some unit tests for the bug fixes added
* it also contains my earlier adaptions to import a file containing the TLEs for a single object received from https://celestrak.com 

Sorry for the formatting diffs. I'll try to resolve them. give me some time...

### CODE REVIEW

**Comment by RobertK66** [comment]
Ok, I can't clean the file ParserTLE.cs. My Visual Studio does not show the whitespace diff at all. To get rid of this mess you could use the github feature 'Diff Settings' - 'Hide whitespace changes'. Then the sync between left and right view gets a lot better......

**Comment by 1manprojects** [comment]
Thanks for your contributions and the tests, I'm currently going through the changes and if everything is fine merge with master and create a new release.

**Comment by 1manprojects** [comment]
To your question in the EpochTimeTest:
`[TestCase("2018-12-31 12:00:00,000", 2019, 0.5)]    // Should this work? It's mentioned here: https://celestrak.com/columns/v04n03/#FAQ02 `

An epoch of (2019, 0.5) should be the first day of the year 2019 at 12:00 UTC. The Epoch of (2019, 0.0) can be seen as the 31. December 2018 at 24:00 UTC or 1.January 2019 at 0:00 UTC.

**Comment by RobertK66** [comment]
I understood this: 

>  An epoch of 98000.00000000 would actually correspond to the beginning of 1997 December 31—strange as that might seem.

so that my testcase should generate 31.12. 12:00 because my 0.5 is half a day later as the 'beginning of 31. December' ...

But I didn't fix this in code, so the testcase is commented out......

**Comment by 1manprojects** [comment]
Most DateTimes can be confusing. This programme does not use an exact same representation as described on celestrack. I made some alterations to make it easier to understand. Thus I made the alteration that 120.5 is the 120th day at 12:00 UTC and 120.0 is the 120th day at 0:00

**Comment by 1manprojects** [comment]
Thanks again for your contribution and the Tests you wrote. your Changes have been merged to Master and will be included in the next release in 1-2 days.

**Comment by RobertK66** [comment]
Yes and you are correct with 1.0 is the first day of the year 0:00(1.1.yyyy 00:00:00) so the values from 0.0 to 1.0 do not make sense, because they would point to the last day of previous year. Per definition this would be a valid TLE- dayofyear.
But in my real world data this does not matter at all, because it seems that NORAD does never generate such 'strange' DayOfYear values. The data i received from celestrak looks like this:

>1 42784U 17036V   17365.60095827  .00001363  00000-0  64078-4 0  9993
2 42784  97.4257  62.9399 0011144 308.3304  51.6929 15.21234676 29034
1 42784U 17036V   17365.73251445  .00001344  00000-0  63261-4 0  9999
2 42784  97.4257  63.0696 0011137 307.8111  52.2116 15.21234942 29051
1 42784U 17036V   18001.12718256  .00001341  00000-0  63093-4 0  9998
2 42784  97.4256  63.4588 0011126 306.2629  53.7578 15.21236098 29118
1 42784U 17036V   18001.58762832  .00001372  00000-0  64494-4 0  9997
2 42784  97.4256  63.9128 0011096 304.4312  55.5875 15.21237631 29189

it 'jumps' from 17365.73...  to 18001.127....
So I think the code is sufficient to be used here....

**Pull request merged**
